// Next
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// CSS
import './globals.css';
import { UserProvider } from '@/context/userContextProvider';
import { cookies } from 'next/headers';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookiesStore = await cookies();
    const token = cookiesStore.get(
        process.env.SPOTIFY_CALLBACK_COOKIES as string
    )?.value;

    return (
        <html lang='en' className='dark'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <UserProvider tokenValue={token}>{children}</UserProvider>
            </body>
        </html>
    );
}
